---
kind: ImageStream
apiVersion: v1
metadata:
  name: wildfly-centos7
spec:
  tags:
  - name: latest
    annotations:
      description: wildfly-builder image stream
      iconClass: icon-jboss
      tags: java,widlfly,galleon
      version: 'latest'
    from:
      kind: DockerImage
      name: "quay.io/jfdenise/wildfly-centos7:latest"
  - name: "17.0"
    annotations:
      description: wildfly-builder image stream
      iconClass: icon-jboss
      tags: java,widlfly,galleon
      version: '17.0'
    from:
      kind: DockerImage
      name: "quay.io/jfdenise/wildfly-centos7:17.0"